# Generated by Django 5.2.5 on 2025-10-24 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-zА-Яа-я-\\s]+$')], verbose_name='Автор')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('counrty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна рождения')),
                ('photo', models.ImageField(height_field=200, null=True, upload_to='images', verbose_name='Фото автора', width_field=200)),
                ('avatar', models.BinaryField(null=True, verbose_name='Аватарка автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('year', models.DateField(verbose_name='Год издания')),
                ('cover', models.ImageField(height_field=300, null=True, upload_to='images', verbose_name='Обложка', width_field=200)),
                ('file', models.FileField(null=True, upload_to='pdf', verbose_name='Файл книги')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('id_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibWebApp.author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'managed': True,
            },
        ),
    ]
