# Generated by Django 4.2.23 on 2025-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibWebApp', '0002_alter_author_photo_alter_book_cover_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='Обложка в БД'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_media/images', verbose_name='Фото автора'),
        ),
    ]
