# Generated by Django 4.2.23 on 2025-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSales', '0002_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
