# Generated by Django 5.2.6 on 2025-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=50, verbose_name='FIO')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start date')),
            ],
        ),
    ]
