# Generated by Django 4.2.25 on 2025-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('homeworld', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
